const mockEvents = {
  city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257
  },
  events: [
    {
      created: 1564472388000,
      duration: 30600000,
      id: "263577205",
      name: "Global Day of Coderetreat @ ThoughtWorks Munich",
      rsvp_limit: 70,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1573889400000,
      local_date: "2019-11-16",
      local_time: "08:30",
      rsvp_open_offset: "PT673H",
      updated: 1564748617000,
      utc_offset: 3600000,
      waitlist_count: 2,
      yes_rsvp_count: 70,
      venue: {
        id: 25852478,
        name: "ThoughtWorks Munich ",
        lat: 48.135372161865234,
        lon: 11.613633155822754,
        repinned: true,
        address_1: "Bothestraße 11",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1413448074000,
        name: "ThoughtWorks Munich",
        id: 17658472,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "ThoughtWorks-Muenchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/ThoughtWorks-Muenchen/events/263577205/",
      description:
        "<p>Welcome to the Global Day of Coderetreat in Munich on Saturday November 16th at ThoughtWorks Munich!</p> <p>On Saturday, November 16th, Coderetreats will be held in cities around the world for the 2019 Global Day of Coderetreat, uniting software developers in their quest for improvement. It also happens to be the 10 year anniversary of this format. Write code, learn from others, teach someone else, and expand your network of friends who are passionate about their craft. Software developers of all skill levels and backgrounds are welcome!</p> <p>What to Bring: Please bring your laptop with your favorite development tools (IDE, version control) and a unit test framework, everything else is provided.</p> <p>Background: Coderetreat is a worldwide pattern designed to hone software skills and design practices through repeated attempts to build an implementation of a well-known software problem (for example Conway's Game of Life). Unit testing and Test-Driven Development will be emphasized as key practices. Developers use pair programming and discussion to exchange knowledge, and additional constraints are given throughout the day to emphasize good design concepts and practices.</p> <p>More details about the format and intention at https://www.coderetreat.org/</a></p> <p>Code of Conduct: We are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, programming language, ability, ethnicity, socioeconomic status, and religion (or lack thereof). And so we invite all those who participate in our event to help us create safe and positive experiences for everyone. Therefore please:<br/>Be welcoming, friendly, and patient.<br/>Be respectful. Not all of us will agree with each other all the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot allow that frustration to turn into a personal attack.<br/>Be aware of the effect your words may have on others. We are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behavior aren't acceptable.</p> <p>Agenda: We will open the doors at 8:30am and offer a little breakfast until we will start the program at 9:30am. Lunch, coffee and beverages will be provided, so you will be able to concentrate on coding the whole day. There will be three sessions in the morning and three sessions after lunch. The official program will end around 5:00pm.</p> ",
      how_to_find_us:
        "The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1572344845000,
      duration: 7200000,
      id: "266042622",
      name: "Technology Radar Vol. 21 Presentation",
      rsvp_limit: 140,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574877600000,
      local_date: "2019-11-27",
      local_time: "19:00",
      updated: 1573049111000,
      utc_offset: 3600000,
      waitlist_count: 14,
      yes_rsvp_count: 140,
      venue: {
        id: 25852478,
        name: "ThoughtWorks Munich ",
        lat: 48.135860443115234,
        lon: 11.613353729248047,
        repinned: true,
        address_1: "Bothestraße 11",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1413448074000,
        name: "ThoughtWorks Munich",
        id: 17658472,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "ThoughtWorks-Muenchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/ThoughtWorks-Muenchen/events/266042622/",
      description:
        "<p>*** Registrations via our website ***<br/>https://www.thoughtworks.com/technology_radar_21_de</a></p> <p>Adopt, trial, assess or hold?<br/>Get ahead of the latest technology trends.</p> <p>The Technology Radar, based on our observations, conversations and experiences with our customers, covers both existing and emerging technologies.</p> <p>The report divides the trends into four groups: Techniques, platforms, tools, programming languages and frameworks. Within these groups, each trend has a recommendation: Hold for technologies that are not initially recommended for use; Assess for technologies that require further evaluation; Trial for technologies that are ready for use; and Adopt for mature technologies.</p> <p>Learn more about the latest technology and join us for the event in our Munich office.</p> <p>We are looking forward to welcome you!</p> <p>Agenda:</p> <p>18:30 - 19:00 Registration and Drinks</p> <p>19:00 - 20:30 Technology Radar Presentation (incl. Q&amp;A)</p> <p>20:30 - 22:00 Get Together with drinks &amp; fingerfood</p> <p>The presentation will be held in English.</p> <p>---</p> <p>*** Registrierung über unsere Website ***<br/>https://www.thoughtworks.com/de/technology_radar_21_de</a></p> <p>Adopt, trial, assess oder hold?<br/>Erfahre von unseren Experten mehr zu den neuesten Technologietrends.</p> <p>Der Technology Radar, der auf unseren Beobachtungen, Gesprächen und Erfahrungen mit unseren Kunden beruht, behandelt sowohl existierende als auch neu aufkommende Technologien.</p> <p>Der Report teilt die Trends in vier Gruppen auf: Techniken, Plattformen, Tools sowie Programmiersprachen und Frameworks. Innerhalb dieser Gruppen wird jeder Trend mit einer Empfehlung versehen: „Hold“ für Technologien, von deren Verwendung vorerst abgeraten wird; „Assess“ für Technologien, die einer weiteren Evaluation bedürfen; „Trial“ für Technologien, die einsatzbereit sind und „Adopt“ für ausgereifte Technologien.</p> <p>Erfahre mehr über die neusten Technologietrends und melde dich für unsere Technology Radar Präsentation in München an.</p> <p>Wir freuen uns auf dich!</p> <p>Agenda:</p> <p>18:30 - 19:00 Registrierung und Drinks</p> <p>19:00 - 20:30 Technology Radar Präsentation (inkl. Q&amp;A)</p> <p>20:30 - 22:00 Get Together mit Drinks &amp; Fingerfood</p> <p>Die Präsentation findet auf Englisch statt.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1573465178000,
      duration: 7200000,
      id: "266379229",
      name: "Deep Fakes 2.0 - How Neural Networks are Changing our World",
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1575394200000,
      local_date: "2019-12-03",
      local_time: "18:30",
      updated: 1573584962000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 22,
      group: {
        created: 1565272185000,
        name: "OpenValue München",
        id: 32563109,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "OpenValueMuenchen",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/OpenValueMuenchen/events/266379229/",
      description:
        "<p>Imagine looking into a mirror and not seeing your own face. Instead, you are looking in the eyes of Barack Obama or Angela Merkel. Your facial expressions are seamlessly transferred to that other person's face in real time.</p> <p>The TNG Hardware Hacking Team has managed to create a prototype that transfers faces from one person to another in real time, based on Deep Fakes. Neural networks detect faces within a video input, then translate them and integrate them back to the video output. Through this technique, it is possible to project deceptively real imitations onto other people. For this purpose, we used Keras trained autoencoder networks and various face recognition algorithms. In the talk, Thomas Endres and Martin Förtsch will give an entertaining and vivid introduction into the world of real-time Deep Fakes. In doing so, they particularly focus on the deep learning techniques used in within the application. Several live demonstrations will complete this event.</p> <p>Keywords: Tensorflow, OpenCV, Keras, UNet, MobileNet, Transfer Learning, Deep Learning, Autoencoder, Realtime Deepfake</p> ",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1571223250000,
      duration: 7200000,
      id: "265709123",
      name: "Best Startups from Hamburg - Pitchnight#1 - München",
      rsvp_limit: 200,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1579111200000,
      local_date: "2020-01-15",
      local_time: "19:00",
      updated: 1571770971000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 44,
      group: {
        created: 1571221326000,
        name: "Wow Yes Startups - München",
        id: 32898396,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "wow-yes-Startups-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/wow-yes-Startups-Munchen/events/265709123/",
      description:
        "<p>HAMBURG’S BEST STARTUPS VISIT MUNICH</p> <p>we connect startups with matching investors.</p> <p>Wir laden alle Startups, Investoren und sonstige Interessierte herzlich ein, an diesem Abend dabei zu sein!</p> <p>Die fünf Gewinner unserer Hamburger Startup Competition pitchen ihr Business vor interessierten Investoren und Publikum in München. Wir freuen uns auf einen tollen Abend in entspannter Atmosphäre!</p> <p>Ablauf:</p> <p>Beginn um 19:00 Uhr<br/>Pitch eines erfolgreichen, lokalen Startups<br/>5 Pitches der besten Hamburger Startups<br/>Q&amp;A mit Münchner Investoren und Startup Community<br/>Lokale Jury wählt das Gewinnerstartup des Abends<br/>Networking an der Bar<br/>Ende um 22:00 Uhr</p> <p>Alle Infos zu uns und unseren Events findest Du hier: https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/</a></p> <p>******************************************</p> <p>ENGLISH</p> <p>You are a startup, investor or just curious about the startup community? Then you are cordially invited to meet Hamburg’s best startups in Munich!</p> <p>The five winners of our Hamburg Startup Competition will pitch their business in front of interested investors and the public in Munich. We are looking forward to a great evening in a relaxed atmosphere!</p> <p>Agenda:</p> <p>Start at 7 p.m.<br/>Pitch of a successful, local startup<br/>5 pitches from Hamburg’s best startups<br/>Q&amp;A with Munich investors and startup community<br/>Local jury selects the winner startup of the evening<br/>Networking at the bar<br/>End at 10 p.m.</p> <p>You can find all information about us and our events here: https://www.meetup.com/de-DE/wow-yes-Startups-Munchen/</a></p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1571126564000,
      duration: 10800000,
      id: "265679947",
      name: "Monero Munich Stammtisch",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1576778400000,
      local_date: "2019-12-19",
      local_time: "19:00",
      updated: 1572199782000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      group: {
        created: 1510658046000,
        name: "Monero Munich",
        id: 26595449,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Monero-Munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/Monero-Munich/events/265679947/",
      description:
        "<p>Hello Monero enthusiasts,</p> <p>this is our regular monthly meetup, where we get together and discuss the latest news.</p> <p>Please RVSP if you're planning to come and shoot me a message if you have any questions.</p> <p>Looking forward to it!</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1572423470000,
      duration: 10800000,
      id: "266070731",
      name: "Event-Driven REST APIs ",
      rsvp_limit: 220,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574875800000,
      local_date: "2019-11-27",
      local_time: "18:30",
      updated: 1572534786000,
      utc_offset: 3600000,
      waitlist_count: 84,
      yes_rsvp_count: 220,
      venue: {
        id: 25683907,
        name: "MAN Truck & Bus Deutschland GmbH",
        lat: 48.180694580078125,
        lon: 11.596031188964844,
        repinned: true,
        address_1: "Oskar-Schlemmer-Straße 19-21",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1399578043000,
        name: "Microservices Meetup Munich",
        id: 14341692,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Microservices-Meetup-Munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Microservices-Meetup-Munich/events/266070731/",
      description:
        "<p>Vaughn Vernon: Event-Driven REST APIs</p> <p>Please keep your RSVP up to date, free spots are always in demand!</p> <p>We will meet at 6:30pm at the canteen of RIO – a Brand of Volkswagen Truck &amp; Bus (MAN Truck &amp; Bus building), with drinks and pizza.</p> <p>The talk starts at 7pm and will be in English.<br/>After the talk we have time for drinks and conversations.</p> <p>Abstract<br/>When should you use request-response and when should you use messaging instead? What if you could use REST for everything, including Event-Driven Architectures?</p> <p>Learn how to design REST APIs that support both conventional human user interfaces and services, and those that support Event-Driven, and more generally, Message-Driven Architectures. As a bonus, expect to pick up tips on Reactive programming. This session is about REST API design for request-response and event-driven microservices with Domain Events using Event Sourcing and CQRS.</p> <p>Bio:<br/>Vaughn, Founder and Chief Architect of Kalele, is the visionary behind the vlingo/PLATFORM. A software developer with more than 35 years of experience in a broad range of business domains, Vaughn is a leading expert in Domain-Driven Design (DDD), and a champion of simplicity and reactive systems. As a consultant and teacher of DDD and Reactive software development, he has helped thousands of developers and numerous teams and organizations. He leads clients to realize innovative, business-driven, reactive, digital systems, as they transform from a legacy of brittle, technology-driven, stagnation. Vaughn is the author of three books: Implementing Domain-Driven Design, Domain-Driven Design Distilled, and Reactive Messaging Patterns with the Actor Model, all published by Addison-Wesley.</p> <p>Location:<br/>Canteen, entrance via<br/>Walter-Gropius-Straße 19<br/>https://goo.gl/maps/y7rRtWyikmm</a></p> ",
      how_to_find_us: "Canteen, Walter-Gropius-Str. 19",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1572885755000,
      duration: 7200000,
      id: "266207271",
      name: "17. Treffen der Gruppe Software Architektur München",
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1575999000000,
      local_date: "2019-12-10",
      local_time: "18:30",
      updated: 1572886100000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 38,
      venue: {
        id: 25881465,
        name: "TNG Technology Consulting GmbH",
        lat: 48.15310287475586,
        lon: 11.616222381591797,
        repinned: true,
        address_1: "Arabellastraße 4a",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1473607978000,
        name: "Software Architektur München",
        id: 20413739,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Software-Architektur-Muenchen",
        who: "Software-Gestalter",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Software-Architektur-Muenchen/events/266207271/",
      description:
        "<p>Liebe Mitglieder der Meetup-Gruppe Software Architektur München,</p> <p>unser nächstes Treffen steht an und wir haben zwei spannende Vorträge:</p> <p>Vortrag: Rettet den Mud-olith!<br/>Sprecher: Daniel Götz und Peter Gafert</p> <p>Vortrag: Qualitäts-Türchen statt Quality-Gates<br/>Sprecher: Florian Deißenböck</p> <p>Abstracts finden sich wie immer auf unsere Seite https://swa-muc.de/</a></p> <p>Wir werden uns am 10. Dezember 2019 um 18:30 Uhr in den Räumen von TNG Technology Consulting GmbH in der Arabellastraße treffen:</p> <p>Arabellastraße 4a<br/>81925 München</p> <p>ca. 3 Minuten von der U-Bahn-Haltestelle der U4 / Arabellapark weg, mit dem Auto kann man hier parken: https://en.parkopedia.com/parking/locations/arabellastraße_4a_81925_münchen_deutschland_u283bq4bkek/?arriving=[masked]&amp;leaving=[masked]</a></p> <p>Für Getränke und Essen ist gesorgt.</p> ",
      how_to_find_us:
        "https://www.tngtech.com/tng-ueber-uns/anfahrt.html#c20978",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1573215558000,
      duration: 7200000,
      id: "266314095",
      name:
        "Läuft bei dir - Routineaufgaben mit RPA und KI ganz einfach automatisieren!",
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574784000000,
      local_date: "2019-11-26",
      local_time: "17:00",
      updated: 1573215558000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 11,
      venue: {
        id: 25799146,
        name: "Criterion",
        lat: 48.104759216308594,
        lon: 11.600908279418945,
        repinned: true,
        address_1: "Aschauer Str. 30",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1518441164000,
        name: "Materna Digital Hub in München",
        id: 27486139,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Materna-Digital-Hub-Muenchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Materna-Digital-Hub-Muenchen/events/266314095/",
      description:
        "<p>Wir laden Sie herzlich ein zu unserem After-Work-Event „Materna Digital hub“ in München am 26. November 2019 ab 17.00 Uhr!</p> <p>RPA wird von immer mehr Organisationen verwendet, um die Produktivität an PC-Arbeitsplätzen durch Automatisierung weiter zu verbessen.</p> <p>Seine wahren Vorteile spielt RPA erst aus, wenn Sie kognitive Intelligenz, maschinelles Lernen und robotergesteuerte Prozessautomatisierung kombinieren. Damit befreien Sie Mitarbeiter von wiederkehrenden Aufgaben, steigern die Effizienz an den Arbeitsplätzen und senken gleichzeitig die Fehlerrate bei manuellen Dateneingaben.</p> <p>Damit Sie sich ein konkretes Bild von der Leistungsfähigkeit einer solchen Lösung machen können, zeigen wir Ihnen eine Live-Demo auf Basis der Software Automation Anywhere.</p> <p>Das erwartet Sie am 26. September von 17:00 bis 20:00 Uhr<br/> Robotic Process Automation vs. Makro-Rekorder: Was ist RPA und warum ist das jetzt (wieder) ein Hype-Thema? (Materna)<br/> Robotic Process Automation oder API: Für jeden Anwendungsfall die richtige Automatisierung (Materna)<br/> Anwendungsfälle für Robotic Process Automation sowie Demo (Materna)<br/> Next-level Robotic Process Automation: Wie bringt Automation Anywhere cognitive in die Automatisierung? Vorstellung kognitiver RPA-Anwendungsfälle und IQBot Demo (Automation Anywhere)</p> <p>Im Anschluss freuen wir uns auf den Austausch bei Canapés und Co.</p> <p>Die Teilnahme ist kostenlos für Sie.</p> ",
      how_to_find_us:
        "Der Weg zu den Räumlichkeiten wird im Gebäude ausgeschildert",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1572527524000,
      duration: 10800000,
      id: "266105534",
      name: "Open-Source-Treffen – TPM, Systemd und Gnome",
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574442000000,
      local_date: "2019-11-22",
      local_time: "18:00",
      updated: 1572606674000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      venue: {
        id: 26710936,
        name: "Cafe Netzwerk",
        lat: 48.09679412841797,
        lon: 11.515952110290527,
        repinned: true,
        address_1: "Schertlinstr. 4",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1430244529000,
        name: "Münchner Open-Source-Treffen",
        id: 18567748,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Open-Source-Treffen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munchen-Open-Source-Treffen/events/266105534/",
      description:
        "<p>Jeder vierte Freitag im Monat für freie Software!<br/>Vorträge dieses mal:</p> <p>~~~ TPMs am Beispiel vom Raspberry Pi ~~~<br/>Mit TPMs kann man sicher Schlüssel im Computer ablegen, und so trusted computing oder Secureboot ermöglichen.</p> <p>~~~ Starten von GNOME mit systemd (Benjamin Berg) ~~~<br/>Mit GNOME 3.34 wird die GNOME Session Standardmäßig mit Hilfe von<br/>Systemd gestartet. Dies bringt einige Vorteile im Bezug auf das<br/>Prozessmanagement, es gab aber auch einige Stolpersteine in der<br/>Implementierung.<br/>Im Vortrag werden einige der Konzepte und Lösungen vorgestellt die es<br/>ermöglichen eine GNOME Session mit Hilfe von systemd zu managen.</p> <p>Im Anschluss an den Vortrag gibt es wie immer einen gemütlichen Austausch, sowie ein Treffen der Münchner FSFE-Gruppe.</p> <p>Die Teilnahme ist kostenlos. Das Café Netzwerk bietet günstige alkoholfreie Getränke sowie Pizzen und Snacks zum kleinen Preis.</p> <p>*** ACHTUNG: NEUE ADRESSE! ***</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1568023019000,
      duration: 10800000,
      id: "264686712",
      name: "Monero Munich Stammtisch",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574359200000,
      local_date: "2019-11-21",
      local_time: "19:00",
      updated: 1572720136000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 25929238,
        name: "Georgios der Grieche",
        lat: 48.119449615478516,
        lon: 11.548611640930176,
        repinned: true,
        address_1: "Implerstraße 47",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1510658046000,
        name: "Monero Munich",
        id: 26595449,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Monero-Munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/Monero-Munich/events/264686712/",
      description:
        "<p>Hello Monero enthusiasts,</p> <p>this is our regular monthly meetup, where we get together and discuss the latest news.</p> <p>We'll meet at a greek restaurant called 'Georgios der Grieche', which is directly at the metro station Implerstraße. See www.georgiosdergrieche.de for more information.</p> <p>Please RVSP if you're planning to come and shoot me a message if you have any questions.</p> <p>Looking forward to it!</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1571642958000,
      duration: 7200000,
      id: "265832961",
      name: "Beer, Brotzeit and IoT @ Concept Reply",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1576778400000,
      local_date: "2019-12-19",
      local_time: "19:00",
      updated: 1571928832000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 74,
      venue: {
        id: 26066109,
        name: "Luise-Ullrich-Straße 14",
        lat: 48.14474868774414,
        lon: 11.538175582885742,
        repinned: true,
        address_1: "Luise-Ullrich-Straße 14",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1508251656000,
        name: "München IoT Meetup",
        id: 26294946,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Muenchen-IoT-Meetup",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/Muenchen-IoT-Meetup/events/265832961/",
      description:
        "<p>WE HAVE A BRAND NEW VENUE! Please come on over and take a look :)</p> <p>Agenda:</p> <p>19:00: Just enough time to grab a beer and snack<br/>19:15: Alyosh Alex Agarwal (Senior Consultant for Big Data Analytics, AI, ML currently working at Mercedes-Benz/Daimler) - IoT within Recommendation Engines in the Automobile Industry<br/>19:45 Andreas Kammerloher (Engineering Consultant at Pixida GmbH) - Nerves: Craft and deploy bulletproof embedded IoT software in Elixir<br/>20:15: Networking/Banter</p> <p>Food and drink served throughout. All presentations in English.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1572297319000,
      duration: 7200000,
      id: "266031559",
      name: "Be Social And Start Somewhere - Speaker night",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574186400000,
      local_date: "2019-11-19",
      local_time: "19:00",
      updated: 1572944981000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 60,
      venue: {
        id: 26210014,
        name: "Stylight GmbH",
        lat: 48.15055847167969,
        lon: 11.54757308959961,
        repinned: true,
        address_1: "Nymphenburger Str. 86",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1562594665000,
        name: "Tech For Good Munich",
        id: 32343555,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Tech-For-Good-Munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/Tech-For-Good-Munich/events/266031559/",
      description:
        "<p>From refugees and migrants without a roof in their new country to leaky roofs in the slums of Africa, our speakers in this edition give back their dignity to the disadvantaged - Social-Bee by providing professional reinsertion and Start Somewhere by giving durable housing, one concrete block at a time.</p> <p>Mathias Wiedemann, Sales &amp; Business Development<br/>Social-Bee is a social business that takes corporate social responsibility with the goal to make the world better, integrating refugees and migrants by providing job opportunities. As a non-profit organization, they reinvent the model of temporary work in a social way. They hire the disadvantaged and place them in companies. The resulting income is used to provide care and training for the refugees. The goal is to offer a stable contract after 1.5 years at the latest.<br/>Every life matters - with every job they create perspectives and promote a colorful society.<br/>https://www.social-bee.de/</a></p> <p>Oliver Von Malm, Kristina Cress, and Silvia Hesse<br/>Start Somewhere is a non-profit limited organization from Munich with eight years of experience in development cooperation in one of the largest slums in Africa: Kibera, Nairobi (Kenya). The vision of Start Somewhere is the sustainable improvement of living conditions in the slums of this world. In concrete terms, Start Somewhere is developing a flexible, reusable, cost-effective and fireproof construction system for buildings in slums. The resulting hollow concrete blocks can be assembled and disassembled by hand as a modular, mortarless plug-in system. For the first time, any angle can also be realized steplessly in the floor plan.<br/>http://www.startsomewhere.eu/en/</a><br/>https://vimeo.com/312915595</a></p> <p>We open the doors at 7.00pm<br/>Talk at 7.30 pm<br/>Followed by discussion and networking</p> <p>Drinks and food will be sponsored by our awesome host, Stylight!</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1573206641000,
      duration: 7200000,
      id: "266312400",
      name: "Startup Legal: Feedback from Munich's Top Startup Lawyers",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1574184600000,
      local_date: "2019-11-19",
      local_time: "18:30",
      updated: 1573512028000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 40,
      venue: {
        id: 26052175,
        name: "Wayra Germany GmbH",
        lat: 48.13779830932617,
        lon: 11.571670532226562,
        repinned: false,
        address_1: "Kaufingerstraße 15",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1370899368000,
        name: "Munich Startup Founder 101",
        id: 8871972,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munich-Startup-Founder-101",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Munich-Startup-Founder-101/events/266312400/",
      description:
        "<p>If you are interested in understanding how to set-up a company the right way, then join us for Startup Legal. Ask your startup legal questions to local experts, and get informed answers. What is the most appropriate type of company to start? How do you deal with cofounders, initial team members and employees? What agreements should you have in place when you start, and what pitfalls should you avoid?</p> <p>&gt;&gt; Our guest speakers for this event include:<br/>- Pascal Schweizer (CEO, Thermosome GmbH)<br/>- Silvio Mc Miken (Rechtsanwalt | Counsel , Reed Smith LLP)<br/>- Martin Sundermann (Partner, Osborne Clarke)</p> <p>&gt;&gt; Who Should Attend?<br/>- Anyone interested in incorporating an early-stage company<br/>- Anyone that wants an understanding of basic corporate law<br/>- Anyone who has questions about incubator/accelerator legal agreements</p> <p>&gt;&gt; What are some of the Topics?<br/>- When should you incorporate your company<br/>- What are the steps to incorporate a business<br/>- What agreements should you understand as a founder<br/>- How do you handle cofounders, team members and employees<br/>- and more...</p> <p>&gt;&gt; This event is FREE, and we expect over 50 people in attendance. For more information, visit http://fi.co/e/211951/meetup</a></p> <p>---</p> <p>For information about the investors, incubators, and tech events available, see our list of Startup Resources (https://fi.co/startup_resources</a>). Interested in perfecting your pitch? Read our Pitch Deck Guide (https://fi.co/pitch_deck</a>) and download templates.</p> <p>---</p> <p>This event is sponsored by the Founder Institute startup accelerator. Founder Institute provides a step-by-step program that gives startup founders the structure, mentor support, and network of entrepreneurs they need to start an enduring company. Based in Silicon Valley and with chapters across 65 countries, the Founder Institute's mission is to Globalize Silicon Valley and build sustainable startup ecosystems worldwide.</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1571293653000,
      duration: 10800000,
      id: "265735738",
      name: "AI for Business Meetup #1 in München",
      rsvp_limit: 90,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1579798800000,
      local_date: "2020-01-23",
      local_time: "18:00",
      updated: 1573064810000,
      utc_offset: 3600000,
      waitlist_count: 8,
      yes_rsvp_count: 90,
      venue: {
        id: 26285058,
        name: "LinkedIn Munich",
        lat: 48.13643264770508,
        lon: 11.571603775024414,
        repinned: true,
        address_1: "Sendlinger Str. 12",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1571225713000,
        name: "AI for Business in München - Use cases and Networking",
        id: 32898601,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "AI-for-Business-in-Munchen-Use-cases-and-Networking",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/AI-for-Business-in-Munchen-Use-cases-and-Networking/events/265735738/",
      description:
        "<p>Unser erstes AI for Business Meetup findet am 23. Januar 2020 in München statt.</p> <p>Wir haben bereits viele erfolgreiche Meetups in Zürich, Bern und Berlin gehabt und freuen uns nun riesig auf eine (neue) Community in München.</p> <p>Unsere Agenda ist gefüllt mit 2 super Speakern und einem tollen Apero, (von LinkedIn Learning organisiert).</p> <p>18:00 - Einlass &amp; Registrierung</p> <p>18:30 - Keynote - tbd.</p> <p>18:45 - Stephan Bail - Talk tbd</p> <p>19:15 - Marco Hochstrasser - AI für Predictive Analytics</p> <p>19:45 - Snacks, Drinks, Networking</p> <p>21:00 - Veranstaltungsende</p> <p>Wenn ihr unsere Speaker bereits vorher kennen lernen wollt, dann schaut auf LinkedIn vorbei:<br/>Stephan Bail: https://www.linkedin.com/in/stephan-bail/</a><br/>Marco Hochstrasser: https://www.linkedin.com/in/mhochstr/</a></p> <p>Und wir sind natürlich auch bereits auf LinkedIn vertreten. Hier gibts regelmässig News und Updates rund um den Einsatz von Künstliche Intelligenz im Business.<br/>https://www.linkedin.com/company/ai-zurich/</a></p> <p>Bis bald<br/>Eure Sophie Hundertmark</p> <p>P.S.: Verpasst nicht unsere Grosse AI FOR BUSINESS KONFERENZ am[masked] in Zürich.<br/>https://ai-zurich.ch/</a><br/>(Für alle Nicht-CH Gäste gibt es die Zürich Card für 3 Tage dazu geschenkt.)</p> ",
      how_to_find_us:
        "Zugang in der Hofstatt-Einkaufspassage (direkt neben Depot)",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1571982461000,
      duration: 7200000,
      id: "bksmkryzpbvb",
      name: "Weekend Coffee for Startup People",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1573916400000,
      local_date: "2019-11-16",
      local_time: "16:00",
      updated: 1571982461000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      venue: {
        id: 26033912,
        name: "Park Café",
        lat: 48.1423454284668,
        lon: 11.56462287902832,
        repinned: true,
        address_1: "Sophienstraße 7",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1443569671000,
        name: "Munich Startup Ecosystem by StartupBlink",
        id: 18980890,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "StartupBlink-Munchen",
        who: "Startup Heroes",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/StartupBlink-Munchen/events/bksmkryzpbvb/",
      description:
        "<p>This event brings together a small group of local entrepreneurs over a cup of coffee in a relaxing and informal atmosphere.</p> <p>Here you will have an opportunity to introduce your business and ideas and not only listen but TALK as well. It is your chance to meet with other participants from diverse industries and find the resources you need, be that business connections, new co-founder, encouragement to start a freelancing career or even ideas on selling.</p> <p>Unlike other Startup events, Weekend Coffee success is solely based on participants attendance and willingness to lead the event, therefore, by RSVPing, you are not only ensuring your seat, but become the event itself. So, make sure to arrive as other attendees are counting on you!</p> <p>Besides that, some of the events are organized by our City Partners https://citypartner.startupblink.com</a> or by local volunteers. If you are willing to lead this event every weekend, we will grant you admin rights so you can set the time and day of your choice. Send us a quick email at [masked]</p> <p>Huamei will be your Event Leader this time.</p> <p>Remember to check the comments below for updates and to find the group on the day of the event. If you arrive first at the cafe, just pick a table and post in the comments section below where you are sitting and how to identify you (e.g. shirt color).</p> <p>Enjoy your coffee with new friends!<br/>_ _ _</p> <p>Do you Telegram?<br/>Join the conversation in our global startup chat and connect with entrepreneurs from all over the world. https://t.me/workjams</a></p> <p>_ _ _</p> <p>Looking for more networking opportunities?<br/>Join a coworking space to increase your work efficiency and meet your new clients, team members, and investors. Our partners at WeWork have an exclusive offer for you in over 600 locations around the world.<br/>Schedule a free tour and apply through this link to get up to 15% discount.<br/>https://wework.startupblink.com</a></p> ",
      how_to_find_us:
        "Know a better location for this meetup? Just send us a message, and we'll change it for you!",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1571982461000,
      duration: 7200000,
      id: "bksmkryzpbnc",
      name: "Weekend Coffee for Startup People",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1575126000000,
      local_date: "2019-11-30",
      local_time: "16:00",
      updated: 1571982461000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
        id: 26033912,
        name: "Park Café",
        lat: 48.1423454284668,
        lon: 11.56462287902832,
        repinned: true,
        address_1: "Sophienstraße 7",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1443569671000,
        name: "Munich Startup Ecosystem by StartupBlink",
        id: 18980890,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "StartupBlink-Munchen",
        who: "Startup Heroes",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/StartupBlink-Munchen/events/bksmkryzpbnc/",
      description:
        "<p>This event brings together a small group of local entrepreneurs over a cup of coffee in a relaxing and informal atmosphere.</p> <p>Here you will have an opportunity to introduce your business and ideas and not only listen but TALK as well. It is your chance to meet with other participants from diverse industries and find the resources you need, be that business connections, new co-founder, encouragement to start a freelancing career or even ideas on selling.</p> <p>Unlike other Startup events, Weekend Coffee success is solely based on participants attendance and willingness to lead the event, therefore, by RSVPing, you are not only ensuring your seat, but become the event itself. So, make sure to arrive as other attendees are counting on you!</p> <p>Besides that, some of the events are organized by our City Partners https://citypartner.startupblink.com</a> or by local volunteers. If you are willing to lead this event every weekend, we will grant you admin rights so you can set the time and day of your choice. Send us a quick email at [masked]</p> <p>Huamei will be your Event Leader this time.</p> <p>Remember to check the comments below for updates and to find the group on the day of the event. If you arrive first at the cafe, just pick a table and post in the comments section below where you are sitting and how to identify you (e.g. shirt color).</p> <p>Enjoy your coffee with new friends!<br/>_ _ _</p> <p>Do you Telegram?<br/>Join the conversation in our global startup chat and connect with entrepreneurs from all over the world. https://t.me/workjams</a></p> <p>_ _ _</p> <p>Looking for more networking opportunities?<br/>Join a coworking space to increase your work efficiency and meet your new clients, team members, and investors. Our partners at WeWork have an exclusive offer for you in over 600 locations around the world.<br/>Schedule a free tour and apply through this link to get up to 15% discount.<br/>https://wework.startupblink.com</a></p> ",
      how_to_find_us:
        "Know a better location for this meetup? Just send us a message, and we'll change it for you!",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1571982461000,
      duration: 7200000,
      id: "bksmkryzqbkb",
      name: "Weekend Coffee for Startup People",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1575730800000,
      local_date: "2019-12-07",
      local_time: "16:00",
      updated: 1571982461000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26033912,
        name: "Park Café",
        lat: 48.1423454284668,
        lon: 11.56462287902832,
        repinned: true,
        address_1: "Sophienstraße 7",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1443569671000,
        name: "Munich Startup Ecosystem by StartupBlink",
        id: 18980890,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "StartupBlink-Munchen",
        who: "Startup Heroes",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/StartupBlink-Munchen/events/bksmkryzqbkb/",
      description:
        "<p>This event brings together a small group of local entrepreneurs over a cup of coffee in a relaxing and informal atmosphere.</p> <p>Here you will have an opportunity to introduce your business and ideas and not only listen but TALK as well. It is your chance to meet with other participants from diverse industries and find the resources you need, be that business connections, new co-founder, encouragement to start a freelancing career or even ideas on selling.</p> <p>Unlike other Startup events, Weekend Coffee success is solely based on participants attendance and willingness to lead the event, therefore, by RSVPing, you are not only ensuring your seat, but become the event itself. So, make sure to arrive as other attendees are counting on you!</p> <p>Besides that, some of the events are organized by our City Partners https://citypartner.startupblink.com</a> or by local volunteers. If you are willing to lead this event every weekend, we will grant you admin rights so you can set the time and day of your choice. Send us a quick email at [masked]</p> <p>Huamei will be your Event Leader this time.</p> <p>Remember to check the comments below for updates and to find the group on the day of the event. If you arrive first at the cafe, just pick a table and post in the comments section below where you are sitting and how to identify you (e.g. shirt color).</p> <p>Enjoy your coffee with new friends!<br/>_ _ _</p> <p>Do you Telegram?<br/>Join the conversation in our global startup chat and connect with entrepreneurs from all over the world. https://t.me/workjams</a></p> <p>_ _ _</p> <p>Looking for more networking opportunities?<br/>Join a coworking space to increase your work efficiency and meet your new clients, team members, and investors. Our partners at WeWork have an exclusive offer for you in over 600 locations around the world.<br/>Schedule a free tour and apply through this link to get up to 15% discount.<br/>https://wework.startupblink.com</a></p> ",
      how_to_find_us:
        "Know a better location for this meetup? Just send us a message, and we'll change it for you!",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1573738822000,
      duration: 5400000,
      id: "266462136",
      name: "Save the date: Weihnachtsglühweintreffen der Munich Legal Hackers",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1576778400000,
      local_date: "2019-12-19",
      local_time: "19:00",
      updated: 1573738822000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 11,
      venue: {
        id: 26732784,
        name: "Wittelsbacherplatz",
        lat: 48.1432991027832,
        lon: 11.57608699798584,
        repinned: false,
        address_1: "Wittelsbacherpl.",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1473061527000,
        name: "Munich Legal Hackers",
        id: 20389421,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "munich-legal-hackers",
        who: "Legal Hackers",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/munich-legal-hackers/events/266462136/",
      description:
        "<p>Wir treffen uns zum Jahresausklang und Glühwein. Vss. auf dem Mittelaltermarkt am Wittelsbacherplatz, München</p> <p>Details to follow.</p> <p>Stefan &amp; Paul für die Munich Legal Hackers</p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1569835687000,
      duration: 10800000,
      id: "265279508",
      name: "Mobility and Location Intelligence ",
      rsvp_limit: 95,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1575394200000,
      local_date: "2019-12-03",
      local_time: "18:30",
      updated: 1569930234000,
      utc_offset: 3600000,
      waitlist_count: 1,
      yes_rsvp_count: 101,
      venue: {
        id: 26052175,
        name: "Wayra Germany GmbH",
        lat: 48.13779830932617,
        lon: 11.571670532226562,
        repinned: true,
        address_1: "Kaufingerstraße 15",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1551172295000,
        name: "Geomob Munich #geomobMUC",
        id: 31257448,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Geomob-Munich-geomobMUC",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link: "https://www.meetup.com/Geomob-Munich-geomobMUC/events/265279508/",
      description:
        "<p>Welcome to the 4th Geomob of the year! This time we meet at Wayra for an evening filled with awesome talks and spatial conversations!</p> <p>The goal of #geomobMUC will be the same as #geomob London and Barcelona: to provide a forum to learn and exchange ideas about interesting services and projects that deal with location. Everyone working in or curious about the location space or with location services is welcome, you do not need to be some sort of GIS expert (though GIS experts are of course welcome as well). What I am most interested in is not pure geo technology, but rather the application of new geo technologies in services and product of all kind. The goal is not pitch presentations or marketing, but rather interesting talks by doers about their experiences.</p> <p>The talks are a chance to learn, but equally important is the dialogue between the attendees.</p> <p>Come by and join us!</p> <p>####################################################################<br/>AGENDA: Great talks, interesting discussions and drinks!<br/>####################################################################</p> <p>We will follow the time-tested #geomob format followed in London and Barcelona with a slight change</p> <p>Doors open at 18.30. All talks will be in English.</p> <p>(A) Alex Barth, Mapbox</p> <p>(B) To be announced</p> <p>(C) To be announced</p> <p>Lighting Talks</p> <p>(i) To be announced<br/>(ii) To be announced</p> <p>Interested in speaking at the event? Send us an email at [masked]</p> <p>Afterward, we will host a discussion and networking session. Looking forward to getting everyone connected with each other!</p> <p>####################################################################<br/>Spread the word and stay updated<br/>####################################################################</p> <p>Please tell everyone you know who may find the evening interesting. Subscribe on our website to stay updated about all events https://thegeomob.com/</a></p> <p>Our low-volume mailing list serves as a way to remind you of upcoming #geomobs and share brief post-event summaries. https://thegeomob.com/mailing-list</a></p> ",
      visibility: "public",
      member_pay_fee: false
    },
    {
      created: 1571904644000,
      duration: 32400000,
      id: "265920923",
      name: "Devs meet Shopware 6",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1575619200000,
      local_date: "2019-12-06",
      local_time: "09:00",
      updated: 1572423587000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 12,
      venue: {
        id: 26192467,
        name: "Design Offices München Nove",
        lat: 48.14472579956055,
        lon: 11.538229942321777,
        repinned: true,
        address_1: "Luise-Ullrich-Straße 14",
        city: "München",
        country: "de",
        localized_country_name: "Germany"
      },
      group: {
        created: 1571770711000,
        name: "Shopware Developers München",
        id: 32925628,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Shopware-Developers-Muenchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin"
      },
      link:
        "https://www.meetup.com/Shopware-Developers-Muenchen/events/265920923/",
      description:
        "<p>Du bist neugierig auf Shopware 6, weißt aber nicht, wo Du anfangen sollst? Du bist (noch) kein Teil des Shopware-Ökosystems? Dann solltest Du unser Developer Event “Meet Shopware 6” nicht verpassen. Wir zeigen Dir, was uns an Shopware begeistert, warum wir es lieben, mit Shopware zu arbeiten und warum auch Du es lieben wirst. Wenn Du mit Symfony, Bootstrap und Vue.js vertraut bist, wirst Du Dich wie zu Hause fühlen. Auch wenn nicht - die Entwicklung mit Shopware 6 fühlt sich extrem intuitiv an*. Während des Events werden wir es beweisen: Du wirst die Shopware-Entwickler treffen und wir werden gemeinsam erste Erweiterungen bauen.</p> <p>Beginne Deine Reise mit Shopware 6 noch heute - Registriere Dich hier: https://www.shopware.com/en/devs-meet-shopware-6-munich/</a></p> <p>Bitte beachte: Das Dev Event wird auf Englisch sein, die Shopware Entwickler sprechen natürlich auch Deutsch.</p> <p>Voraussetzungen:<br/>- Laptop<br/>- Running Shopware developer setup<br/>- Basic knowledge on Symfony &amp; Vue.js<br/>- Curiosity &amp; Team spirit</p> <p>Agenda:<br/>09:00 - 09:30 am: Opening and a small breakfast<br/>09:30 - 10:30 am: Welcome and Kickoff Shopware 6<br/>10:30 - 12:00 am: Onboarding Development Shopware 6<br/>12:00 - 12:45 am: Lunch<br/>12:45 - 04:45 pm: Development Session Shopware 6<br/>04:45 - 05:15 pm: Recap / Q&amp;A Session<br/>05:15 - 06:00 pm: Networking</p> <p>Jetzt kostenlos registrieren: https://www.shopware.com/en/devs-meet-shopware-6-munich/</a></p> ",
      visibility: "public",
      member_pay_fee: false
    }
  ]
};

export { mockEvents };
